CREATE TABLE [dbo].[Permisos]
(
	IdPermiso INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_IdPermiso PRIMARY KEY CLUSTERED(IdPermiso),
	IdRol INT NOT NULL CONSTRAINT FK_Permisos_Roles FOREIGN KEY(IdRol) REFERENCES dbo.Roles(IdRol),
	Mantenimiento BIT NOT NULL
	
)
WITH (DATA_COMPRESSION = PAGE)
GO
