CREATE TABLE [dbo].[PRODUCTS]
(
	[IDPRODUCTO] INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Proveedor PRIMARY KEY CLUSTERED(IDPRODUCTO),
	[CODIGO] [varchar](10) NOT NULL ,
	[DESCRIPCION] [varchar](300) NOT NULL,
	[UNIDAD] [varchar](20) NOT NULL,
	[CANTIDADDISPONIBLE] [float] NOT NULL,
	[PRECIOCOMPRA] [float] NOT NULL,
	[PRECIOVENTA] [float] NOT NULL,
	[COSTOTOTAL] [float] NOT NULL 
)
