CREATE TABLE [dbo].[PRODUCTS]
(
	[CODIGO] [varchar](10) NOT NULL CONSTRAINT PK_Codigo PRIMARY KEY CLUSTERED([CODIGO]) UNIQUE,
	[DESCRIPCION] [varchar](300) NOT NULL,
	[UNIDAD] [varchar](20) NOT NULL,
	[CANTIDAD_DISPONIBLE] [float] NOT NULL,
	[PRECIO_COMPRA] [float] NOT NULL,
	[PRECIO_VENTA] [float] NOT NULL,
	[COSTO_TOTAL] [float] NOT NULL 
)
