CREATE TABLE [dbo].[PRODUCTS]
(
	[IDPRODUCTO] INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Proveedor PRIMARY KEY CLUSTERED(IDPRODUCTO),
	[CODIGO] [varchar](10) NOT NULL ,
	[DESCRIPCION] [varchar](300) NOT NULL,
	[UNIDAD] [varchar](20) NOT NULL,
	[CANTIDAD_DISPONIBLE] [float] NOT NULL,
	[PRECIO_COMPRA] [float] NOT NULL,
	[PRECIO_VENTA] [float] NOT NULL,
	[COSTO_TOTAL] [float] NOT NULL 
)
