CREATE TABLE [dbo].[Roles]
(
	IdRol INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_IdRol PRIMARY KEY CLUSTERED(IdRol),
	Rol VARCHAR(50) NOT NULL,
	Taller VARCHAR(50) NOT NULL,
	Personal VARCHAR(50) NOT NULL,
	Bitacoras VARCHAR(50) NOT NULL
)
WITH (DATA_COMPRESSION = PAGE)
GO
