CREATE PROCEDURE [dbo].[ProductsUpdate]
	@IDPRODUCTO INT,
	@CODIGO VARCHAR(10),
	@DESCRIPCION VARCHAR(300),
	@UNIDAD VARCHAR(20),
	@CANTIDAD_DISPONIBLE FLOAT,
	@PRECIO_COMPRA FLOAT,
	@PRECIO_VENTA FLOAT,
	@COSTO_TOTAL FLOAT

AS
 BEGIN
  SET NOCOUNT ON

  BEGIN TRANSACTION TRASA

  BEGIN TRY

  UPDATE dbo.PRODUCTS SET
      CODIGO = @CODIGO
	, DESCRIPCION = @DESCRIPCION
	, UNIDAD = @UNIDAD
	, CANTIDAD_DISPONIBLE = @CANTIDAD_DISPONIBLE
	, PRECIO_COMPRA = @PRECIO_COMPRA
	, PRECIO_VENTA = @PRECIO_VENTA 
	, COSTO_TOTAL = @COSTO_TOTAL 
  WHERE
     @IDPRODUCTO = @IDPRODUCTO

  COMMIT TRANSACTION TRASA
  SELECT 0 AS CodeError, '' AS MsgError

  END TRY

	  BEGIN CATCH
		SELECT 
			   ERROR_NUMBER() AS CodeError,
			   ERROR_MESSAGE() AS MsgError

	  ROLLBACK TRANSACTION TRASA
  
  END CATCH

  END 