CREATE PROCEDURE [dbo].[ProductsList]
AS
BEGIN 
	SET NOCOUNT ON
	SELECT 
		CODIGO
  	, DESCRIPCION		  
	, UNIDAD
	, CANTIDAD_DISPONIBLE
	, PRECIO_COMPRA
	, PRECIO_VENTA
	, COSTO_TOTAL  
	FROM
	    dbo.PRODUCTS
END