CREATE PROCEDURE [dbo].[ProductsUpdate]
	@IDPRODUCTO INT,
	@CODIGO VARCHAR(10),
	@DESCRIPCION VARCHAR(300),
	@UNIDAD VARCHAR(20),
	@CANTIDADDISPONIBLE FLOAT,
	@PRECIOCOMPRA FLOAT,
	@PRECIOVENTA FLOAT,
	@COSTOTOTAL FLOAT

AS
 BEGIN
  SET NOCOUNT ON

  BEGIN TRANSACTION TRASA

  BEGIN TRY

  UPDATE dbo.PRODUCTS SET
      CODIGO = @CODIGO
	, DESCRIPCION = @DESCRIPCION
	, UNIDAD = @UNIDAD
	, CANTIDADDISPONIBLE = @CANTIDADDISPONIBLE
	, PRECIOCOMPRA = @PRECIOCOMPRA
	, PRECIOVENTA = @PRECIOVENTA 
	, COSTOTOTAL = @COSTOTOTAL 
  WHERE
     @IDPRODUCTO = @IDPRODUCTO

  COMMIT TRANSACTION TRASA
  SELECT 0 AS CodeError, '' AS MsgError

  END TRY

	  BEGIN CATCH
		SELECT 
			   ERROR_NUMBER() AS CodeError,
			   ERROR_MESSAGE() AS MsgError

	  ROLLBACK TRANSACTION TRASA
  
  END CATCH

  END 