CREATE PROCEDURE [dbo].[ProductsRead]
	@IDPRODUCTO INT = NULL
AS
BEGIN 
	SET NOCOUNT ON

	SELECT 
	      CODIGO
  	, DESCRIPCION		  
	, UNIDAD
	, CANTIDAD_DISPONIBLE
	, PRECIO_COMPRA
	, PRECIO_VENTA
	, COSTO_TOTAL  
	FROM
	    dbo.PRODUCTS
	WHERE
	    (@IDPRODUCTO IS NULL OR IDPRODUCTO = @IDPRODUCTO)
	      

END
